server:
  port: 8081

spring:
  config:
    import:
      - application-mariadb.yml
  application:
    name: bloomnote-upload-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true

minio:
  url: http://192.168.0.25:9000
  access-user: admin
  access-password: minioAdmin
  bucket-name: bloomnote

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        authentication: DEBUG
#        web: DEBUG
#    com:
#      bloomnote: DEBUG