server:
  port: 8082

spring:
  config:
    import:
      - application-mariadb.yml
  application:
    name: bloomnote-external-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true

cron:
  trend: "*/30 * * * * *"

feign:
  service:
    album: http://localhost:8081

storage:
  url: http://192.168.0.25:9000
  bucket: bloomnote
  ai-server: http://58.236.116.237:5000

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        authentication: DEBUG
#        web: DEBUG
#    com:
#      bloomnote: DEBUG