server:
  port: 8080

spring:
  config:
    import:
      - application-jwt.yml
      - application-mariadb.yml
  application:
    name: bloomnote-user-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true